// <auto-generated />
using BookDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookDB.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookDB.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Hải Dờ",
                            CategoryId = 1,
                            Description = "Đàn ông tuổi 15 mo ước thành đàn ông tuổi 20, đàn ông tuổi 20 mo ước thành đàn ông tuổi 30, đàn ông tuổi 30 mo ước được trở thành đàn ông tuổi 40 và đàn ông tuổi 40 lại mo ước đặt chân lên cỗ máy thời gian để quay lại tuổi 30 với toàn bộ tài sản của mình. Vậy đấy!",
                            Image = "cuocsong.svg",
                            Price = 61000m,
                            Title = "Cuộc Sống Rất Giống Cuộc Đời"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Lê Xuân Viết",
                            CategoryId = 2,
                            Description = "Hướng dẫn lập trình từ cơ bản đến nâng cao cho người mới bắt đầu.",
                            Image = "laptrinh.svg",
                            Price = 85000m,
                            Title = "Lập Trình Không Khó"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Cay Horstmann",
                            CategoryId = 2,
                            Description = "Sách học Java nền tảng dành cho lập trình viên chuyên nghiệp.",
                            Image = "java.svg",
                            Price = 120000m,
                            Title = "Core Java Fundamentals, Volume 1"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Nguyễn An",
                            CategoryId = 1,
                            Description = "Những câu chuyện truyền cảm hứng về cuộc sống ý nghĩa.",
                            Image = "songdungnghia.svg",
                            Price = 55000m,
                            Title = "Sống Đúng Nghĩa"
                        });
                });

            modelBuilder.Entity("BookDB.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Cuộc sống"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Lập trình"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sức khỏe"
                        });
                });

            modelBuilder.Entity("BookDB.Models.Book", b =>
                {
                    b.HasOne("BookDB.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookDB.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
